menu_last_game = minetest
selected_world_path = /home/rfuerza954/.minetest/worlds/kk
update_last_known = 5015001
update_last_checked = 1774826939
enable_damage = true
creative_mode = false
server_announce = false
